# Template of an application

include:
  # Components
  - local: "/gitlab-ci/components/technical/.docker.yml"
  - local: "/gitlab-ci/components/ci/.pre-process.yml"
  - local: "/gitlab-ci/components/ci/.publish.yml"
  - local: "/gitlab-ci/components/ci/.build.yml"
  - local: "/gitlab-ci/components/ci/.quality.yml"
  - local: "/gitlab-ci/components/ci/.workflow.yml"

stages:
  - build 🛠️
  - quality ✅
  - publish 🚀

variables:
  B2B: "false"

#################
# Job to extend #
#################

.publish:appaloosa:feature:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:FTR
  rules:
    - when: manual
      allow_failure: true # Allows to display the status OK even if the stage publish is not executed

# Publish an application on Appaloosa in REC environment
.publish:appaloosa:rec:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:REC
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: manual

# Publish an application on Appaloosa in NRG environment
.publish:appaloosa:nrg:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:NRG
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $B2B == "false" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: always
    - if: '$B2B == "false" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on Appaloosa in internal HML environment
.publish:appaloosa:hml:internal:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:HML_INTERNAL
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: always
    - if: '$B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on Appaloosa in external HML environment
.publish:appaloosa:hml:external:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:HML_EXTERNAL
  rules:
    - if: '$B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on the App Store in PROD environment
.publish:app-store:hml:external:
  extends:
    - .gitrise
    - .publish:app-store
  variables:
    BITRISE_VARS: ENV:HML_EXTERNAL
  rules:
    - if: '$B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on Appaloosa in PROD environment
.publish:appaloosa:prod:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:PROD_INTERNAL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual

# Publish an application on the App Store in PROD environment
.publish:app-store:prod:
  extends:
    - .gitrise
    - .publish:app-store
  variables:
    BITRISE_VARS: ENV:PROD
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual

# Publish an application on the Play Store in PROD environment
.publish:play-store:prod:
  extends:
    - .gitrise
    - .publish:play-store
  variables:
    BITRISE_VARS: ENV:PROD_EXTERNAL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual
