# Template of an application

include:
  # Components
  - local: "/gitlab-ci/components/.docker.yml"
  - local: "/gitlab-ci/components/.publish.yml"
  - local: "/gitlab-ci/components/.build.yml"
  - local: "/gitlab-ci/components/.quality.yml"
  - local: "/gitlab-ci/components/.workflow.yml"

stages:
  - build 🛠️
  - quality ✅
  - publish 🚀

variables:
  B2B: "false"

#################
# Job to extend #
#################

# Publish an application on Appaloosa in REC environment
.publish_appaloosa_rec:
  extends:
    - .gitrise
    - .publish_appaloosa
  variables:
    BITRISE_VARS: ENV:REC
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: manual

# Publish an application on Appaloosa in NRG environment
.publish_appaloosa_nrg:
  extends:
    - .gitrise
    - .publish_appaloosa
  variables:
    BITRISE_VARS: ENV:NRG
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $B2B == "false" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: always
    - if: '$B2B == "false" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on Appaloosa in internal HML environment
.publish_appaloosa_hml_internal:
  extends:
    - .gitrise
    - .publish_appaloosa
  variables:
    BITRISE_VARS: ENV:HML_INTERNAL
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: always
    - if: '$B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on Appaloosa in external HML environment
.publish_appaloosa_hml_external:
  extends:
    - .gitrise
    - .publish_appaloosa
  variables:
    BITRISE_VARS: ENV:HML_EXTERNAL
  rules:
    - if: '$B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on the App Store in PROD environment
.publish_app_store_hml_external:
  extends:
    - .gitrise
    - .publish_app_store
  variables:
    BITRISE_VARS: ENV:HML_EXTERNAL
  rules:
    - if: '$B2B == "true" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
    - when: never

# Publish an application on Appaloosa in PROD environment
.publish_appaloosa_prod:
  extends:
    - .gitrise
    - .publish_appaloosa
  variables:
    BITRISE_VARS: ENV:PROD_INTERNAL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual

# Publish an application on the App Store in PROD environment
.publish_app_store_prod:
  extends:
    - .gitrise
    - .publish_app_store
  variables:
    BITRISE_VARS: ENV:PROD
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual

# Publish an application on the Play Store in PROD environment
.publish_play_store_prod:
  extends:
    - .gitrise
    - .publish_play_store
  variables:
    BITRISE_VARS: ENV:PROD_EXTERNAL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: manual
