# Modules Template

include:
  # Components
  - local: "/gitlab-ci/components/.docker.yml"
  - local: "/gitlab-ci/components/.publish.yml"
  - local: "/gitlab-ci/components/.build.yml"

stages:
  - build 🛠️
  - quality ✅
  - publish 🚀

#################
# Job to extend #
#################

# Publish a module currently in develop state 
.publish_artifactory_dev:
  extends:
    - .gitrise
    - .publish_artifactory
  variables:
    BITRISE_VARS: TYPE:DEV
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - when: manual
      allow_failure: true # Allows to display the status OK even if the stage publish is not executed

# Publish a module currently in release_candidte state
.publish_artifactory_rc:
  extends:
    - .gitrise
    - .publish_artifactory
  variables:
    BITRISE_VARS: TYPE:RC
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      when: always
    - when: manual
      allow_failure: true # Allows to display the status OK even if the stage publish is not executed

# Publish a module currently in release_candidte state
.publish_artifactory_rel:
  extends:
    - .gitrise
    - .publish_artifactory
  variables:
    BITRISE_VARS: TYPE:REL
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      when: always
    - when: manual
      allow_failure: true # Allows to display the status OK even if the stage publish is not executed
