# Modules Template

include:
  # Components
  - local: "/gitlab-ci/components/technical/.docker.yml"
  - local: "/gitlab-ci/components/technical/.gradle.yml"
  - local: "/gitlab-ci/components/ci/.pre-process.yml"
  - local: "/gitlab-ci/components/ci/.publish.yml"
  - local: "/gitlab-ci/components/ci/.build.yml"
  - local: "/gitlab-ci/components/ci/.quality.yml"
  - local: "/gitlab-ci/components/ci/.workflow.yml"

stages:
  - pre-process ⚙
  - build 🛠️
  - quality ✅
  - publish 🚀

####################
# Job to implement #
####################

# Check the branch name
# check:branch_ame:
#   extends:
#     - .check:branch_ame

#################
# Job to extend #
#################

# Publish a module feature on artifactory
.publish:artifactory:ftr:
  extends:
    - .gitrise
    - .publish:artifactory
  variables:
    BITRISE_VARS: TYPE:FTR
  rules:
    - when: manual

# Publish a module in demo-app on appaloosa
.publish:appaloosa:ftr:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: TYPE:FTR
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: manual

# Publish a module from develop in release state
.publish:artifactory:rel:
  extends:
    - .gitrise
    - .publish:artifactory
  variables:
    BITRISE_VARS: TYPE:DEV
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - when: manual

# Publish a module from develop in release state
.publish:artifactory:fix:
  extends:
    - .gitrise
    - .publish:artifactory
  variables:
    BITRISE_VARS: TYPE:FIX
  rules:
    - when: manual
