# Template of an application

include:
  # Components
  - local: "/gitlab-ci/components/ci/.publish.yml"
  - local: "/gitlab-ci/components/ci/.build.yml"
  - local: "/gitlab-ci/components/ci/.workflow.yml"
  - local: "/gitlab-ci/components/ci/.stages.yml"
  - local: "/gitlab-ci/components/ci/.authorize.yml"
  - local: "/gitlab-ci/components/technical/.gitrise.yml"
  - local: "/gitlab-ci/components/ci/.notify.yml"
  - local: "/gitlab-ci/components/ci/.debug.yml"
  - local: "/gitlab-ci/components/ci/.quality.yml"
  - local: "/gitlab-ci/components/ci/.application.yml"

variables:
  BITRISE_APP_SLUG: $BITRISE_APP_SLUG_DEV

# debug 🛠️

.debug:app:
  extends: .debug

# application 📱

.application:app:
  extends: .application

# quality ✅

.quality:end-to-end:app:
  extends: .quality:end-to-end

# build 🏗️

.build:app:
  extends:
    - .gitrise
    - .build
  variables:
    DELIVERY_TYPE: INTERNAL
    BITRISE_VARS: ENV:$ENV,APP:$APP,DELIVERY_TYPE:$DELIVERY_TYPE,CI_PIPELINE_ID:$CI_PIPELINE_ID
  artifacts:
    reports:
      dotenv: bitrise.env

.build:rec:
  extends: .build:app
  variables:
    ENV: REC

.build:ftr:
  extends: .build:app
  variables:
    ENV: FTR

.build:mock:
  extends: .build:app
  variables:
    ENV: MOCK

.build:pentest:
  extends: .build:app
  variables:
    ENV: PENTEST

.build:nrg:
  extends: .build:app
  variables:
    ENV: NRG

.build:hml:adhoc:
  extends: .build:app
  variables:
    ENV: HML

.build:hml:release:
  extends: .build:app
  variables:
    DELIVERY_TYPE: EXTERNAL
    ENV: HML

.build:prod:adhoc:
  extends: .build:app
  variables:
    ENV: PROD

.build:prod:release:
  extends: .build:app
  variables:
    DELIVERY_TYPE: EXTERNAL
    ENV: PROD

# authorization 🔐

.authorize:publish:app:
  extends:
    - .gitrise # use gitrise component to use the gitrise docker image
    - .authorize

# publish 🚀

.publish:appaloosa:app:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:$ENV,APP:$APP,PREVIOUS_APP_SLUG:$PREVIOUS_APP_SLUG,PREVIOUS_BUILD_SLUG:$PREVIOUS_BUILD_SLUG,CI_PIPELINE_ID:$CI_PIPELINE_ID

.publish:appaloosa:rec:
  extends: .publish:appaloosa:app
  variables:
    ENV: REC

.publish:appaloosa:ftr:
  extends: .publish:appaloosa:app
  variables:
    ENV: FTR

.publish:appaloosa:mock:
  extends: .publish:appaloosa:app
  variables:
    ENV: MOCK

.publish:appaloosa:pentest:
  extends: .publish:appaloosa:app
  variables:
    ENV: PENTEST

.publish:appaloosa:nrg:
  extends: .publish:appaloosa:app
  variables:
    ENV: NRG

.publish:appaloosa:hml:adhoc:
  extends: .publish:appaloosa:app
  variables:
    ENV: HML
    BITRISE_APP_SLUG: $BITRISE_APP_SLUG_OPS

.publish:appaloosa:prod:adhoc:
  extends: .publish:appaloosa:app
  variables:
    ENV: PROD
    BITRISE_APP_SLUG: $BITRISE_APP_SLUG_OPS

.publish:play-store:app:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:$ENV,APP:$APP,PREVIOUS_APP_SLUG:$PREVIOUS_APP_SLUG,PREVIOUS_BUILD_SLUG:$PREVIOUS_BUILD_SLUG,DELIVERY_TYPE:$DELIVERY_TYPE
    BITRISE_APP_SLUG: $BITRISE_APP_SLUG_OPS
    DELIVERY_TYPE: EXTERNAL

.publish:play-store:prod:release:
  extends: .publish:play-store:app
  variables:
    ENV: PROD

.publish:app-store:app:
  extends:
    - .gitrise
    - .publish:app-store
  variables:
    BITRISE_VARS: "ENV:$ENV,APP:$APP,PREVIOUS_APP_SLUG:$PREVIOUS_APP_SLUG,PREVIOUS_BUILD_SLUG:$PREVIOUS_BUILD_SLUG,DELIVERY_TYPE:$DELIVERY_TYPE"
    BITRISE_APP_SLUG: $BITRISE_APP_SLUG_OPS
    DELIVERY_TYPE: EXTERNAL

.publish:app-store:hml:release:
  extends: .publish:app-store:app
  variables:
    ENV: HML

.publish:app-store:prod:release:
  extends: .publish:app-store:app
  variables:
    ENV: PROD

# communication 📣

.notify:publish:app:
  extends:
    - .gitrise
    - .notify:publish
  variables:
    DELIVERY_TYPE: INTERNAL
    BITRISE_VARS: "ENV:$ENV,APP:$APP,DELIVERY_TYPE:$DELIVERY_TYPE,CI_PIPELINE_ID:$CI_PIPELINE_ID,OS:$OS"

.notify:publish:rec:
  extends: .notify:publish:app
  variables:
    ENV: REC

.notify:publish:nrg:
  extends: .notify:publish:app
  variables:
    ENV: NRG

.notify:publish:hml:adhoc:
  extends: .notify:publish:app
  variables:
    ENV: HML

.notify:publish:hml:release:
  extends: .notify:publish:app
  variables:
    DELIVERY_TYPE: EXTERNAL
    ENV: HML

.notify:publish:prod:adhoc:
  extends: .notify:publish:app
  variables:
    ENV: PROD

.notify:publish:prod:release:
  extends: .notify:publish:app
  variables:
    ENV: PROD
    DELIVERY_TYPE: EXTERNAL
