# Implementation of an android application

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.app_pipeline.yml"

####################
# Job to implement #
####################

# Build an application
build:
  extends:
    - .gitrise
    - .build
  variables:
    BITRISE_VARS: ENV:REC
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

# Pass the quality of an application on GitLab
quality:
  extends:
    - .grandroid
    - .quality
  before_script:
    - bundle install
  script:
    - echo TODO
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

# Publish an application on Appaloosa in REC environment
# Verify the branch name
check:branch_name:
  extends:
    - .gitrise
    - .check-branch_name

# Publish Appaloosa
publish:appaloosa:feature:
  extends: .publish:appaloosa:feature


# Publish an application on Appaloosa in REC environment
publish:appaloosa:rec:
  extends: .publish:appaloosa:rec

# Publish an application on Appaloosa in NRG environment
publish:appaloosa:nrg:
  extends: .publish:appaloosa:nrg

# Publish an application on Appaloosa in internal HML environment
publish:appaloosa:hml:internal:
  extends: .publish:appaloosa:hml:internal

# Publish an application on Appaloosa in external HML environment
publish:appaloosa:hml:external:
  extends: .publish:appaloosa:hml:external
  needs: ["publish:appaloosa:hml:internal"]

# Publish a PROD application on Appaloosa
publish:appaloosa:prod:
  extends: .publish:appaloosa:prod

# Publish a PROD application on the Play Store
publish:play-store:prod:
  extends: .publish:play-store:prod
