# Android module implementation

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.module_pipeline.yml"

####################
# Job to implement #
####################

# Build an application
build:
  extends:
    - .gitrise
    - .build
  variables:
    BITRISE_VARS: TYPE:DEV
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true
    - when: never

# Pass the quality of an application on GitLab
quality:
  extends:
    - .quality
    - .grandroid
    - .sonar:gradle
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true
    - when: never

publish:artifactory:ftr:
  extends: .publish:artifactory:ftr

publish:appaloosa:ftr:
  extends: .publish:appaloosa:ftr

publish:artifactory:rel:
  extends: .publish:artifactory:rel

publish:artifactory:fix:
  extends: .publish:artifactory:fix
