# Implementation of an android application

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.app-pipeline.yml"

####################
# Job to implement #
####################

build:
  extends: .build:app
  variables:
    APP: "ANY"

# Appaloosa #

publish:appaloosa:all:
  extends: .publish:appaloosa:app
  variables:
    APP: "ALL"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "NRG", "HML_INTERNAL", "HML_EXTERNAL", "PROD"]
  rules:
    - if: '$ENV == "HML_INTERNAL"'
      variables:
        ENV: HML
      when: manual
    - if: '$ENV == "HML_EXTERNAL"'
      variables:
        ENV: HML
        DELIVERY_TYPE: "EXTERNAL"
      when: manual
    - when: manual

publish:appaloosa:axa:
  extends: .publish:appaloosa:app
  variables:
    APP: "AXA"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "HML_INTERNAL", "HML_EXTERNAL", "PROD"]
  rules:
    - if: '$ENV == "HML_INTERNAL"'
      variables:
        ENV: HML
      when: manual
    - if: '$ENV == "HML_EXTERNAL"'
      variables:
        ENV: HML
        DELIVERY_TYPE: "EXTERNAL"
      when: manual
    - when: manual

publish:appaloosa:azb:
  extends: .publish:appaloosa:app
  variables:
    APP: "AZB"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "HML", "PROD"]

publish:appaloosa:bpe:
  extends: .publish:appaloosa:app
  variables:
    APP: "BPE"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "NRG", "PROD"]

publish:appaloosa:ccf:
  extends: .publish:appaloosa:app
  variables:
    APP: "CCF"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "HML", "PROD"]

publish:appaloosa:cmb:
  extends: .publish:appaloosa:app
  variables:
    APP: "CMB"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "NRG", "PROD"]

publish:appaloosa:cmso:
  extends: .publish:appaloosa:app
  variables:
    APP: "CMSO"
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "NRG", "PROD"]

# Play Store #

publish:play-store:all:
  extends: .publish:play-store:app

publish:play-store:axa:
  extends: .publish:play-store:app
  variables:
    APP: "AXA"

publish:play-store:azb:
  extends: .publish:play-store:app
  variables:
    APP: "AZB"

publish:play-store:bpe:
  extends: .publish:play-store:app
  variables:
    APP: "BPE"

publish:play-store:ccf:
  extends: .publish:play-store:app
  variables:
    APP: "CCF"

publish:play-store:cmb:
  extends: .publish:play-store:app
  variables:
    APP: "CMB"

publish:play-store:cmso:
  extends: .publish:play-store:app
  variables:
    APP: "CMSO"
