# Android module implementation

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.module_pipeline.yml"

####################
# Job to implement #
####################

# Build an application
build:
  extends:
    - .gitrise
    - .build
  variables:
    BITRISE_VARS: TYPE:DEV
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true
    - when: never

# Pass the quality of an application on GitLab
quality:
  extends:
    - .quality
    - .grandroid
    - .sonar_gradle
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true
    - when: never

publish_artifactory_ftr:
  extends: .publish_artifactory_ftr

publish_appaloosa_ftr:
  extends: .publish_appaloosa_ftr

publish_artifactory_rel:
  extends: .publish_artifactory_rel

publish_artifactory_fix:
  extends: .publish_artifactory_fix