# Implementation of an android application

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.app_pipeline.yml"

####################
# Job to implement #
####################

# Publish Appaloosa

publish_appaloosa_rec:
  extends: .publish_appaloosa_rec

publish_appaloosa_hml:
  extends: .publish_appaloosa_hml

publish_appaloosa_nreg:
  extends: .publish_appaloosa_nreg

publish_appaloosa_prod:
  extends: .publish_appaloosa_prod

# Publish Play Store

publish_play_store_prod:
  extends: .publish_play_store_prod
