# Implementation of an ios application

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.app-pipeline.yml"

##################
# Job to extends #
##################

.publish:appaloosa:b2b:
  extends: .publish:appaloosa:app
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "HML_INTERNAL"]
  rules:
    - if: '$ENV == "HML_INTERNAL"'
      variables:
        ENV: HML
      when: manual
    - when: manual

.publish:appaloosa:fedes:
  extends: .publish:appaloosa:app
  parallel:
    matrix:
      - ENV: ["FTR", "REC", "NRG"]
  rules:
    - when: manual

####################
# Job to implement #
####################

.publish:app-store:b2b:
  extends: .publish:app-store:app
  parallel:
    matrix:
      - ENV: ["HML_EXTERNAL", "PROD"]
  rules:
    - if: '$ENV == "HML_EXTERNAL"'
      variables:
        ENV: HML
      when: manual
    - when: manual

.publish:app-store:fedes:
  extends: .publish:app-store:app
  parallel:
    matrix:
      - ENV: ["PROD"]
