# Implementation of an ios application

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.app_pipeline.yml"

####################
# Job to implement #
####################

# Build an application
build:
  extends:
    - .gitrise
    - .build
  variables:
    BITRISE_VARS: ENV:REC
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

# Pass the quality of an application on bitrise an download the generated reports on gitlab as artifacts
quality:
  extends:
    - .gitrise_download_artifacts
    - .quality_bitrise
  variables:
    BITRISE_ARTIFACTS_OUTPUT_DIR: sonar-reports
    BITRISE_VARS: ENV:REC,BITRISE_ARTIFACTS_OUTPUT_DIR:$BITRISE_ARTIFACTS_OUTPUT_DIR
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

# Execute sonar scanner to upload source code and reports on sonarqube server (go/sonarqubeprd)
sonar:
  extends:
    - .sonar_scanner_cli
    - .sonar_scanner
  needs: ["quality"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

# Publish an application on Appaloosa in REC environment
publish_appaloosa_rec:
  extends: .publish_appaloosa_rec

# Publish an application on Appaloosa in NRG environment
publish_appaloosa_nrg:
  extends: .publish_appaloosa_nrg

# Publish an application on Appaloosa in internal HML environment
publish_appaloosa_hml_internal:
  extends: .publish_appaloosa_hml_internal

# Publish an application on the App Store in external HML environment
publish_app_store_hml_external:
  extends: .publish_app_store_hml_external
  needs: ["publish_appaloosa_hml_internal"]

# Publish a PROD application on the App Store
publish_app_store_prod:
  extends: .publish_app_store_prod
