# iOS module implementation

include:
  # Template
  - local: "/gitlab-ci/pipelines/templates/.module-pipeline.yml"

####################
# Implemented jobs #
####################

# Build an application
build:
  extends:
    - .gitrise
    - .build
  variables:
    BITRISE_VARS: TYPE:REL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true
    - when: never

# Pass the quality of an application on GitLab
tests:
  extends:
    - .quality:bitrise
    - .gitrise:download-artifacts
  variables:
    BITRISE_ARTIFACTS_OUTPUT_DIR: sonar-reports
  rules:
    - when: manual
      allow_failure: true

sonar:
  extends:
    - .quality
    - .sonar:cli
  rules:
    - when: manual
      allow_failure: true

publish:podspec:ftr:
  extends: .publish:podspec:ftr

publish:podspec:rel:
  extends: .publish:podspec:rel

publish:podspec:fix:
  extends: .publish:podspec:fix

publish:demo:appaloosa:
  extends: .publish:appaloosa:ftr
  rules:
    - when: manual
      allow_failure: true