# Authorize component

.authorize:
  stage: authorization 🔐
  variables:
    CAS_PASSWORD: ""
  script:
    - |
      if [ ! -z "$CAS_PASSWORD" ]
      then
        AOD_TOKEN=$(curl -k -H "user:$GITLAB_USER_LOGIN" -H "password:$CAS_PASSWORD" https://tokens.aaa-p.cloud.arkea.com:8443/tokens/ | jq .token | awk -F '"' '{print $2}')
        AOD_TOKEN_VALIDATION=$(curl -k -H "Authorization: Bearer $AOD_TOKEN" https://tokens.aaa-p.cloud.arkea.com:8443/tokens/validate?token=$AOD_TOKEN)
        IS_VALID_TOKEN=$(echo $AOD_TOKEN_VALIDATION | jq .valid)
        if [ $IS_VALID_TOKEN = true ]
        then
          HABILITATION_LVL=$(echo $AOD_TOKEN_VALIDATION | jq .payload.lvl)
          if [ $HABILITATION_LVL -gt 600 ]
          then
              echo "Vous êtes habilité à déployer en environnement de production"
          else
              echo "Vos habilitations ne sont pas suffisantes, vous ne pouvez pas utiliser ce workflow"
              exit 1
          fi
        else
          echo "Vos habilitations ne sont pas valides, vous ne pouvez pas utiliser ce workflow"
          exit 1
        fi
      else
        echo "Mot de passe pour l'utilisateur '$GITLAB_USER_LOGIN' non renseigné, merci de relancer le workflow avec le mot de passe correspondant dans la variable d'environnement CAS_PASSWORD"
        exit 1
      fi
