# Pro-Process component

#################
# Job to extend #
#################

# Verify the branch name
.check-branch-name:
  stage: pre-process ⚙
  rules:
    - if: '($CI_COMMIT_BRANCH =~ /^\w+-\d{1,4}(_\w+)*$/ || $CI_COMMIT_BRANCH =~ /^tech\/.*/) || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "release"'
      when: never
    - when: always
      allow_failure: false
  script:
    - echo "CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME"
    - echo "CI_COMMIT_BRANCH $CI_COMMIT_BRANCH"
    - echo -e "\033[1;91mWrong branch name, please rename it like this :\n\t- If it's linked to a Jira -> 'JIRA-XXX_desc' (where '_desc' is optional)\n\t- If it's a technical branch -> 'tech/xyz'"
    - exit 1
