# Publish component

#################
# Job to extend #
#################

.publish:
  stage: publish 🚀
  rules:
    - when: manual
      allow_failure: true # Allows to display the status OK even if the stage publish is not executed

# Publish an application on Appaloosa
.publish_appaloosa:
  extends: .publish
  variables:
    BITRISE_WORKFLOW: publish_appaloosa

# Publish an Android application on the Play Store
.publish_play_store:
  extends: .publish
  variables:
    BITRISE_WORKFLOW: publish_play_store

# Publish an iOS application on the App Store 
.publish_app_store:
  extends: .publish
  variables:
    BITRISE_WORKFLOW: publish_app_store

# Publish an iOS application on the App Store 
.publish_artifactory:
  extends: .publish
  variables:
    BITRISE_WORKFLOW: publish_artifactory

