# Quality component

#################
# Job to extend #
#################

# Pass the quality of an application
.quality:
  stage: quality ✅

# Pass the quality of an application on Bitrise
.quality_bitrise:
  extends:
    - .quality
  variables:
    BITRISE_WORKFLOW: quality

# Scan and upload quality on Sonarqube (go/sonarqubeprd)
.sonar_scanner:
  stage: quality ✅