# Quality component

# Pass the quality of an application
.quality:
  stage: quality ✅

# Pass the quality of an application on Bitrise
.quality:bitrise:
  extends:
    - .quality
  variables:
    BITRISE_WORKFLOW: quality

.quality:sonar:
  stage: sonar 📈
