# Quality component

.quality:
  stage: quality ✅

.quality:unit-tests:
  extends: .quality
  variables:
    BITRISE_WORKFLOW: quality

.quality:sonarqube:
  extends: .quality

.quality:end-to-end:
  extends: .quality