# Workflow component

# The workflow of application pipeline
# If GitLab attempts to trigger:
# A merge request pipeline, start the pipeline.
#   For example, a merge request pipeline can be triggered by a push to a branch with an associated open merge request.
# A branch pipeline, but a merge request is open for that branch, do not run the branch pipeline.
#   For example, a branch pipeline can be triggered by a change to a branch, an API call, a scheduled pipeline, and so on.
# A branch pipeline, but there is no merge request open for the branch, run the branch pipeline.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_MERGE_REQUEST_ID'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
