lane :upload_crash_files_on_instana do |params|
    os = params[:os]
    working_dir = params[:working_dir]
    file_name = params[:file_name]
    file_id = params[:file_id]
    config_id = params[:config_id]
    sourcemap_upload_id = params[:sourcemap_upload_id]
    production = params[:production]
    instana_manager(
        os: os,
        working_dir: working_dir,
        file_name: file_name,
        file_id: file_id,
        config_id: config_id,
        sourcemap_upload_id: sourcemap_upload_id,
        production: production
    )
end

lane :notification_gchat do |params|
    message = params[:message]
    is_delivery = params[:is_delivery]
    webhook_url = params[:webhook_url]
    name = params[:name]
    build_env = params[:build_env]
    build_branch = params[:build_branch]
    version_name = params[:version_name]
    build_number = params[:build_number]
    extra_link = params[:extra_link]
    app_icon_url = params[:app_icon_url]
    os_icon_url = params[:os_icon_url]

        gchat_notification_manager(
        message: message,
        is_delivery: is_delivery,
        webhook_url: webhook_url,
        name: name,
        build_env: build_env,
        build_branch: build_branch,
        version_name: version_name,
        build_number: build_number,
        extra_link: extra_link,
        app_icon_url: app_icon_url,
        os_icon_url: os_icon_url
    )
end

lane :process_gitlab_release do |params|
    project_id = params[:project_id]
    tag_name = params[:tag_name]
    app_name = params[:app_name]
    app_version = params[:app_version]
    gitlab_release_manager(
        project_id: project_id, 
        tag_name: tag_name,
        app_name: app_name,
        app_version: app_version
    )
end

lane :write_sonarqube_result_in_mr do |params|
    project_name = params[:project_name]
    sonarqube_decoration(project_name: project_name)
end

lane :download_bitrise_artifacts_from_previous_build do
    download_bitrise_artifacts()
end

lane :protect_gitlab_tag do |params|
    project_id = params[:project_id]
    tag_name = params[:tag_name]
    gitlab_tags_manager(
        project_id: project_id,
        tag_name: tag_name
    )
end