# Quality component

#################
# Job to extend #
#################

# Pass the quality of an application
.quality:
  stage: quality ✅

# Pass the quality of an application on Bitrise
.quality_bitrise:
  extends:
    - .quality
  variables:
    BITRISE_WORKFLOW: quality

# Pass the quality of an application on GitLab
.quality_gitlab:
  extends:
    - .quality
  script:
    # TODO: add quality for android
    - echo TODO

# Scan and upload quality on Sonarqube (go/sonarqubeprd)
.sonar_scanner:
  stage: quality ✅
