# Modules Template

include:
  # Components
  - local: "/gitlab-ci/components/technical/.gitrise.yml"
  - local: "/gitlab-ci/components/technical/.sonar.yml"
  - local: "/gitlab-ci/components/ci/.publish.yml"
  - local: "/gitlab-ci/components/ci/.build.yml"
  - local: "/gitlab-ci/components/ci/.quality.yml"
  - local: "/gitlab-ci/components/ci/.workflow.yml"
  - local: "/gitlab-ci/components/ci/.stages.yml"
  - local: "/gitlab-ci/components/ci/.debug.yml"

variables:
  HAS_DEMO_APP: "true"
  HAS_TESTS: "true"
  BITRISE_ARTIFACTS_OUTPUT_DIR: "quality" # Can be global because there are no other jobs downloading artifacts from bitrise

# debug 🛠️

.debug:app:
  extends: .debug

# quality ✅

.quality:unit-tests:module:
  extends:
    - .gitrise:download-artifacts
    - .quality:unit-tests
  variables:
    ENV: REL
    BITRISE_VARS: ENV:$ENV

.quality:sonarqube:module:
  extends:
    - .sonar:cli
    - .quality:sonarqube
  variables:
    ENV: REL

# build 🏗️

.build:module:
  extends:
    - .gitrise
    - .build
  variables:
    BITRISE_VARS: ENV:$ENV,HAS_TESTS:$HAS_TESTS,HAS_DEMO_APP:$HAS_DEMO_APP,CI_PIPELINE_SOURCE:$CI_PIPELINE_SOURCE
  artifacts:
    reports:
      dotenv: bitrise.env

.build:feature:
  extends: .build:module
  variables:
    ENV: FTR

.build:release:
  extends: .build:module
  variables:
    ENV: REL

# publish 🚀

.publish:artifactory:module:
  extends:
    - .gitrise
    - .publish:artifactory
  variables:
    BITRISE_VARS: ENV:$ENV,PREVIOUS_APP_SLUG:$PREVIOUS_APP_SLUG,PREVIOUS_BUILD_SLUG:$PREVIOUS_BUILD_SLUG

.publish:artifactory:feature:
  extends: .publish:artifactory:module
  variables:
    ENV: FTR

.publish:artifactory:release:
  extends: .publish:artifactory:module
  variables:
    ENV: REL

.publish:appaloosa:module:
  extends:
    - .gitrise
    - .publish:appaloosa
  variables:
    BITRISE_VARS: ENV:$ENV,PREVIOUS_APP_SLUG:$PREVIOUS_APP_SLUG,PREVIOUS_BUILD_SLUG:$PREVIOUS_BUILD_SLUG

.publish:appaloosa:feature:
  extends: .publish:appaloosa:module
  variables:
    ENV: FTR

.publish:podspec:module:
  extends:
    - .gitrise
    - .publish:podspec
  variables:
    BITRISE_VARS: ENV:$ENV,PREVIOUS_APP_SLUG:$PREVIOUS_APP_SLUG,PREVIOUS_BUILD_SLUG:$PREVIOUS_BUILD_SLUG

.publish:podspec:release:
  extends: .publish:podspec:module
  variables:
    ENV: REL
