# Docker component

#################
# Job to extend #
#################

# Load the Gitrise docker image
.gitrise:
  image: docker-registry.s.arkea.com/ccwm/gitrise:latest
  script:
    - gitrise -a "$BITRISE_USER_TOKEN" -s "$BITRISE_APP_SLUG" -w "$BITRISE_WORKFLOW" -b "$CI_COMMIT_REF_NAME" -c "$CI_COMMIT_SHA" --stream -p 10  -e "$BITRISE_VARS"

# Load the Gitrise docker image with the artifacts download option
.gitrise:download-artifacts:
  image: docker-registry.s.arkea.com/ccwm/gitrise:latest
  script:
    - gitrise -a "$BITRISE_USER_TOKEN" -s "$BITRISE_APP_SLUG" -w "$BITRISE_WORKFLOW" -b "$CI_COMMIT_REF_NAME" -c "$CI_COMMIT_SHA" --stream -p 10  -e "$BITRISE_VARS" -o "$BITRISE_ARTIFACTS_OUTPUT_DIR"
  artifacts:
    paths:
      - $BITRISE_ARTIFACTS_OUTPUT_DIR/

# Load the Sonar docker image
.sonar:cli:
  image: docker-registry.s.arkea.com/sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner

# Load the Grandroid docker image
.grandroid:
  image: docker-registry.s.arkea.com/domi/grandroid:master
  before_script:
    - bundle install
