# Sonar component

.sonar:cli:
  image: docker-registry.s.arkea.com/domi/do-mobile/sonarqube
  before_script:
    - git config --global url.https://$KS739_API_USERNAME:$KS739_API_TOKEN@gitlark.s.arkea.com/.insteadOf https://gitlark.s.arkea.com/
    - bundle install
  script:
    - bundle exec fastlane run_sonarqube_analysis --env $ENV
  tags:
    - hiperf
